<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // <<<<< Esto es lo que falta
use Carbon\Carbon;

class IglesiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar la tabla antes de insertar
        DB::table('iglesias')->delete();

        $datosIglesias = [
            // Primer Bloque
            ['codigo' => 11, 'nombre' => 'Avaroa - Bolívar', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-1 Avaroa'],
            ['codigo' => 12, 'nombre' => 'Bolívar Municipal', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-2 Bolívar'],
            ['codigo' => 13, 'nombre' => 'Villa Bolívar "D"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-3 Villa Bolívar D'],
            ['codigo' => 80, 'nombre' => 'Horizontes II', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-4 Horizontes'],
            ['codigo' => 81, 'nombre' => 'Horizontes III', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-5 Horizontes'],
            ['codigo' => 82, 'nombre' => 'La Hermosa', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-6 La Hermosa'],
            ['codigo' => 83, 'nombre' => 'Villa Concepción', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'D-7 Villa Concepción'],
            ['codigo' => 104, 'nombre' => 'Pacajes Caluyo', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Pacajes'],
            ['codigo' => 104, 'nombre' => 'Filial Igachi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Igachi'],
            ['codigo' => 120, 'nombre' => 'El Minero', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'El Minero'],
            ['codigo' => 121, 'nombre' => 'Rosas Pampa', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Rosas Pampa'],
            ['codigo' => 122, 'nombre' => 'Santiago II - Santa Rosa', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Santiago II'],
            ['codigo' => 123, 'nombre' => 'Villa Santa Rosa', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Santa Rosa'],
            ['codigo' => 123, 'nombre' => 'Filial Kera', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Kera'],
            ['codigo' => 100, 'nombre' => 'Alto de la Alianza', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Alto Alianza'],
            ['codigo' => 101, 'nombre' => 'Belén La Primera', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Belén'],
            ['codigo' => 102, 'nombre' => 'Emanuel', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Emanuel'],
            ['codigo' => 103, 'nombre' => 'Maranatha - Pacajes', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Pacajes Maranatha'],
            ['codigo' => 41, 'nombre' => 'Cosmos', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cosmos'],
            ['codigo' => 41, 'nombre' => 'Real del Sur', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Real del Sur'],
            ['codigo' => 42, 'nombre' => 'Nueva Jerusalén', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Nueva Jerusalén'],
            ['codigo' => 146, 'nombre' => 'Villa Alemania HUC', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Alemania'],
            ['codigo' => 142, 'nombre' => 'Luz de Vida', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Luz de Vida'],
            ['codigo' => 43, 'nombre' => 'Primavera', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Primavera'],
            ['codigo' => 44, 'nombre' => 'Villa Juliana', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Juliana'],
            ['codigo' => 40, 'nombre' => '1ro. de Mayo', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => '1ro Mayo'],
            ['codigo' => 140, 'nombre' => 'Collpani', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Collpani'],
            ['codigo' => 141, 'nombre' => 'Ebenezer', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Ebenezer'],
            ['codigo' => 143, 'nombre' => 'Mercedario', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Mercedario'],
            ['codigo' => 144, 'nombre' => 'Unidad Vecinal "C"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'U.V. C'],
            ['codigo' => 144, 'nombre' => 'Filial San Marcos', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Marcos'],
            ['codigo' => 145, 'nombre' => 'Villa Adela', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Adela'],
            ['codigo' => 145, 'nombre' => 'Filial Paraiso', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Paraíso'],
            ['codigo' => 20, 'nombre' => 'Amor de Dios', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Amor de Dios'],
            ['codigo' => 21, 'nombre' => 'Charapaqui', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Charapaqui Central'],
            ['codigo' => 21, 'nombre' => 'San José', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San José'],
            ['codigo' => 22, 'nombre' => 'Charapaqui Sur', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Charapaqui Sur'],
            ['codigo' => 23, 'nombre' => 'Edén', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Edén'],
            ['codigo' => 24, 'nombre' => 'Jesús de Nazareth', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Jesús de Nazareth'],
            ['codigo' => 25, 'nombre' => 'Luz de Victoria', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Luz de Victoria'],
            ['codigo' => 26, 'nombre' => 'Sajama - Charapaqui', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Sajama'],
            ['codigo' => 27, 'nombre' => 'San Luis "A"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Luis A'],
            ['codigo' => 60, 'nombre' => '6 de Junio', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => '6 de Junio'],
            ['codigo' => 61, 'nombre' => 'Central Cupilupaca', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cupilupaca'],
            ['codigo' => 63, 'nombre' => 'Las Delicias', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Las Delicias'],
            ['codigo' => 62, 'nombre' => 'Cumaravi', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cumaravi'],
            ['codigo' => 64, 'nombre' => 'Senac', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Senac'],
            ['codigo' => 65, 'nombre' => 'Villa Aroma', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Aroma'],

            // Segundo Bloque
            ['codigo' => 240, 'nombre' => 'Exaltación - San Martín', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Exaltación SM'],
            ['codigo' => 241, 'nombre' => 'Mercedes "B"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Mercedes B'],
            ['codigo' => 242, 'nombre' => 'Nueva Chijini', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Nueva Chijini'],
            ['codigo' => 243, 'nombre' => 'San Martín', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Martín'],
            ['codigo' => 244, 'nombre' => 'Villa Mercedes "G"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Mercedes G'],
            ['codigo' => 200, 'nombre' => 'Luz de Sión', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Luz de Sión'],
            ['codigo' => 201, 'nombre' => 'Maranatha - Mariscal', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Maranatha'],
            ['codigo' => 202, 'nombre' => 'Mariscal 5k', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Mariscal 5k'],
            ['codigo' => 203, 'nombre' => 'Mariscal 6-25', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Mariscal 6-25'],
            ['codigo' => 204, 'nombre' => 'Mariscal Santa Cruz - Mariscal', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'M. Santa Cruz'],
            ['codigo' => 205, 'nombre' => 'Urkupiña', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Urkupiña'],
            ['codigo' => 220, 'nombre' => 'Nueva Esperanza', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Nueva Esperanza'],
            ['codigo' => 221, 'nombre' => 'Nueva Tilata', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Nueva Tilata'],
            ['codigo' => 221, 'nombre' => 'Filial Villa Belen', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Filial V. Belén'],
            ['codigo' => 221, 'nombre' => 'Filial Viliroco 1', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Viliroco'],
            ['codigo' => 221, 'nombre' => 'Filial Vida 2', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Filial Vida 2'],
            ['codigo' => 221, 'nombre' => 'Filial 24 de junio', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Filial 24 Junio'],
            ['codigo' => 222, 'nombre' => 'San Ignacio', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Ignacio'],
            ['codigo' => 223, 'nombre' => 'Tilata', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Tilata'],
            ['codigo' => 873, 'nombre' => 'Viacha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viacha Central'],
            ['codigo' => 873, 'nombre' => 'Filial Buena Vista', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viacha F. B. Vista'],
            ['codigo' => 873, 'nombre' => 'Filial Ponguini', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viacha F. Ponguini'],
            ['codigo' => 800, 'nombre' => 'Achica Baja', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Achica Baja'],
            ['codigo' => 802, 'nombre' => 'Ancara', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Ancara'],
            ['codigo' => 803, 'nombre' => 'Callisaya - El Salvador', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Callisaya'],
            ['codigo' => 804, 'nombre' => 'Canaviri', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Canaviri'],
            ['codigo' => 804, 'nombre' => 'Filial Choquenaira', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Choquenaira'],
            ['codigo' => 804, 'nombre' => 'Filial Tacagua', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Tacagua'],
            ['codigo' => 804, 'nombre' => 'Filial chuquiñuma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Chuquiñuma'],
            ['codigo' => 805, 'nombre' => 'Jalsuri - El Salvador', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Jalsuri'],
            ['codigo' => 805, 'nombre' => 'Filial Colina Blanca', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Colina Blanca'],
            ['codigo' => 807, 'nombre' => 'Muroamaya - el Salvador', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Muroamaya'],
            ['codigo' => 808, 'nombre' => 'Palcoma Alta - El Salvador', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Palcoma Alta'],
            ['codigo' => 809, 'nombre' => 'Palcoma Centro - Rosario', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Palcoma Centro'],
            ['codigo' => 810, 'nombre' => 'Pan de Azúcar', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Pan de Azúcar'],
            ['codigo' => 882, 'nombre' => 'Surusaya', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Surusaya'],
            ['codigo' => 886, 'nombre' => 'Villa Arriendo', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Arriendo'],
            ['codigo' => 863, 'nombre' => 'Contorno', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Contorno'],
            ['codigo' => 864, 'nombre' => 'Hilata Centro', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Hilata Centro'],
            ['codigo' => 868, 'nombre' => 'Pallina Grande', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Pallina Grande'],
            ['codigo' => 869, 'nombre' => 'Pallina Laja', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Pallina Laja'],
            ['codigo' => 869, 'nombre' => 'Filial Pallina Laja', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Pallina Laja'],
            ['codigo' => 870, 'nombre' => 'Poma Culto', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Poma Culto'],
            ['codigo' => 871, 'nombre' => 'Santa Rosa - Viacha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Santa Rosa Viacha'],
            ['codigo' => 874, 'nombre' => 'Cachuma', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Cachuma'],
            ['codigo' => 875, 'nombre' => 'Cantapa', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Cantapa'],
            ['codigo' => 876, 'nombre' => 'Capiri', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Capiri'],
            ['codigo' => 877, 'nombre' => 'Fabril - Viacha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fabril Viacha'],
            ['codigo' => 878, 'nombre' => 'Sacacani - Viacha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Sacacani Viacha'],
            ['codigo' => 878, 'nombre' => 'Filial Calapunco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Calapunco'],
            ['codigo' => 878, 'nombre' => 'Filial Yanamuyo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Yanamuyo'],
            ['codigo' => 879, 'nombre' => 'Satatotora', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Satatotora'],
            ['codigo' => 880, 'nombre' => 'Viluyo', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Viluyo'],
            ['codigo' => 881, 'nombre' => 'Arca de Noe', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Arca de Noe'],
            ['codigo' => 865, 'nombre' => 'Janco Kala "A"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Janco Kala A'],
            ['codigo' => 866, 'nombre' => 'Janco Kala "B"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Janco Kala B'],
            ['codigo' => 806, 'nombre' => 'Limani', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Limani'],
            ['codigo' => 867, 'nombre' => 'Mariscal Ballivián "A"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'M. Ballivián A'],
            ['codigo' => 872, 'nombre' => 'Sequichuru', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Sequichuru'],
            ['codigo' => 811, 'nombre' => 'Villa Salvador', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Salvador'],
            ['codigo' => 260, 'nombre' => '25 de Julio - Senkata "A"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => '25 de Julio'],
            ['codigo' => 261, 'nombre' => 'Florida - Senkata "A"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Florida'],
            ['codigo' => 262, 'nombre' => 'Panorámica II - Senkata "A"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Panorámica II'],
            ['codigo' => 304, 'nombre' => 'Caracarani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí CERRADO'],
            ['codigo' => 280, 'nombre' => 'Apóstol Santiago', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Apóstol Santiago'],
            ['codigo' => 281, 'nombre' => 'Chijimarca', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Chijimarca'],
            ['codigo' => 282, 'nombre' => 'Cristal I', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cristal I'],
            ['codigo' => 283, 'nombre' => 'Encarnación', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Encarnación'],
            ['codigo' => 284, 'nombre' => 'Porvenir - Senkata "B"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Porvenir'],
            ['codigo' => 285, 'nombre' => 'San Nicolás', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Nicolás'],
            ['codigo' => 286, 'nombre' => 'Senkata 79', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Senkata 79'],
            ['codigo' => 301, 'nombre' => '27 de Septiembre', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí 27 Sep'],
            ['codigo' => 302, 'nombre' => 'Atipiris', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí Atipiris'],
            ['codigo' => 302, 'nombre' => 'Filial Nueva Esperanza', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí F. N. E.'],
            ['codigo' => 302, 'nombre' => 'U.E. Maranata', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí U.E. M.'],
            ['codigo' => 302, 'nombre' => 'Filial Viviendas', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí F. Viviendas'],
            ['codigo' => 0, 'nombre' => 'Filial Amachuma', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Filial Amachuma'], // Código no proporcionado, se usa 0
            ['codigo' => 306, 'nombre' => 'Los Pinos', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Los Pinos'],
            ['codigo' => 307, 'nombre' => 'Remanentes', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Remanentes'],
            ['codigo' => 300, 'nombre' => 'Modelo', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Modelo'],
            ['codigo' => 303, 'nombre' => 'Bethel', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Bethel'],
            ['codigo' => 305, 'nombre' => 'Los Lirios', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí Los Lirios'],
            ['codigo' => 305, 'nombre' => 'Filial Achica', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Potosí', 'zona' => 'Potosí F. Achica'],
            ['codigo' => 403, 'nombre' => 'Mazocruz', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Mazocruz'],
            ['codigo' => 308, 'nombre' => 'Ventilla I', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Ventilla I'],
            ['codigo' => 309, 'nombre' => 'Ventilla II', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Ventilla II'],
            ['codigo' => 321, 'nombre' => '31 de Octubre', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => '31 de Octubre'],
            ['codigo' => 325, 'nombre' => 'La Esperanza', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'La Esperanza'],
            ['codigo' => 320, 'nombre' => '27 de Mayo', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => '27 de Mayo'],
            ['codigo' => 322, 'nombre' => 'Tarapacá "A"', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Tarapacá A'],
            ['codigo' => 323, 'nombre' => 'Tarapacá "B"', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Tarapacá B'],
            ['codigo' => 324, 'nombre' => 'Trinidad', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Beni', 'zona' => 'Trinidad/Beni'], // Ciudad diferente
            ['codigo' => 324, 'nombre' => 'Filial Copacabana', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Copacabana'],
            ['codigo' => 724, 'nombre' => 'Ajoya', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Ajoya'],
            ['codigo' => 725, 'nombre' => 'Calacachi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Calacachi'],
            ['codigo' => 726, 'nombre' => 'Calamarca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Calamarca'],
            ['codigo' => 727, 'nombre' => 'Caluyo Alta', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Caluyo Alta'],
            ['codigo' => 728, 'nombre' => 'Caluyo Baja', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Caluyo Baja'],
            ['codigo' => 728, 'nombre' => 'Filial Chocorosi', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'F. Chocorosi'],
            ['codigo' => 729, 'nombre' => 'Cañuma', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cañuma'],
            ['codigo' => 730, 'nombre' => 'Chocorosi - Villa Remedios', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Chocorosi V.R.'],
            ['codigo' => 731, 'nombre' => 'Choritotora', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Choritotora'],
            ['codigo' => 732, 'nombre' => 'Cosmini', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cosmini'],
            ['codigo' => 733, 'nombre' => 'Cruce Panamericana', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Cruce Panamericana'],
            ['codigo' => 734, 'nombre' => 'Finaya', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Finaya'],
            ['codigo' => 735, 'nombre' => 'Hichuraya Llujturi', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Hichuraya L.'],
            ['codigo' => 736, 'nombre' => 'Huayhuasi - Villa Remedios', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Huayhuasi V.R.'],
            ['codigo' => 737, 'nombre' => 'Llallagua', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Llallagua'],
            ['codigo' => 738, 'nombre' => 'Machacamarca - Villa Remedios', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Machacamarca V.R.'],
            ['codigo' => 738, 'nombre' => 'Filial Ventilla', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'F. Ventilla'],
            ['codigo' => 739, 'nombre' => 'Ninacho', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Ninacho'],
            ['codigo' => 740, 'nombre' => 'Pizacaviña', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Pizacaviña'],
            ['codigo' => 741, 'nombre' => 'Pocohota', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Pocohota'],
            ['codigo' => 742, 'nombre' => 'San Antonio - Villa Remedios', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'San Antonio V.R.'],
            ['codigo' => 742, 'nombre' => 'Filial Senkata Alta', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'F. Senkata Alta'],
            ['codigo' => 743, 'nombre' => 'Sivicani', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Sivicani'],
            ['codigo' => 744, 'nombre' => 'Vilaque', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Vilaque'],
            ['codigo' => 745, 'nombre' => 'Villa Ancara', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Ancara'],
            ['codigo' => 746, 'nombre' => 'Villa Remedios', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Villa Remedios'],
            ['codigo' => 747, 'nombre' => 'Chacoma', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Chacoma'],
            ['codigo' => 747, 'nombre' => 'Filial Hichuraya Grande', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Hichuraya Grande'],
            ['codigo' => 748, 'nombre' => 'Collana', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Collana'],
            ['codigo' => 748, 'nombre' => 'Filial Uncallamaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Uncallamaya'],
            ['codigo' => 748, 'nombre' => 'Filial Panzuri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Panzuri'],
            ['codigo' => 757, 'nombre' => 'Toncopugio', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Toncopugio'],
            ['codigo' => 749, 'nombre' => 'Colquencha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Colquencha'],
            ['codigo' => 750, 'nombre' => 'Hichuraya Alta', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Hichuraya Alta'],
            ['codigo' => 751, 'nombre' => 'Irpuma', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Irpuma'],
            ['codigo' => 752, 'nombre' => 'Iruma Pomani', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Iruma Pomani'],
            ['codigo' => 753, 'nombre' => 'Kella Kella', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Kella Kella'],
            ['codigo' => 754, 'nombre' => 'Marquirivi', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Marquirivi'],
            ['codigo' => 755, 'nombre' => 'Micaya', 'tipo' => 'Iglesia', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Micaya'],
            ['codigo' => 756, 'nombre' => 'Santiago de Llallagua', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Santiago de Llallagua'],
            ['codigo' => 756, 'nombre' => 'Filial Totorani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Totorani'],
            ['codigo' => 843, 'nombre' => 'Achiri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Achiri'],
            ['codigo' => 844, 'nombre' => 'Andaluz', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Andaluz'],
            ['codigo' => 845, 'nombre' => 'Antaquira - Rosario', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Antaquira'],
            ['codigo' => 845, 'nombre' => 'Filial Nueva Esperanza 2', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Nueva Esp. 2'],
            ['codigo' => 845, 'nombre' => 'Filial Acero Marca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Acero Marca'],
            ['codigo' => 845, 'nombre' => 'Filial Huayllani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Huayllani'],
            ['codigo' => 846, 'nombre' => 'Caquiaviri - Rosario', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Caquiaviri'],
            ['codigo' => 847, 'nombre' => 'Casquiri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Casquiri'],
            ['codigo' => 848, 'nombre' => 'Coro Coro - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Coro Coro'],
            ['codigo' => 848, 'nombre' => 'Filial Ballivian 1', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Ballivian 1'],
            ['codigo' => 849, 'nombre' => 'Ejra', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Ejra'],
            ['codigo' => 850, 'nombre' => 'Huaripujo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Huaripujo'],
            ['codigo' => 851, 'nombre' => 'Kari Alta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Kari Alta'],
            ['codigo' => 852, 'nombre' => 'Kasillunca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Altiplano Kasillunca'],
            /****______________________grupo1 */
            // Registros de Rosario (ALTIPLANO, LA PAZ)
            ['codigo' => 853, 'nombre' => 'Llimphi - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Llimphi'],
            ['codigo' => 854, 'nombre' => 'Monte Sión', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Monte Sión'],
            ['codigo' => 855, 'nombre' => 'Muro Pilar', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Muro Pilar'],
            ['codigo' => 856, 'nombre' => 'Nueva Florida - Rosario', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Nueva Florida'],
            ['codigo' => 856, 'nombre' => 'Filial Choco Ninoca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Choco Ninoca'],
            ['codigo' => 857, 'nombre' => 'Pando - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Pando'],
            ['codigo' => 857, 'nombre' => 'Filial Rosa Pata', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Rosa Pata'],
            ['codigo' => 858, 'nombre' => 'Pirapi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Pirapi'],
            ['codigo' => 859, 'nombre' => 'Santa Rosa - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Santa Rosa'],
            ['codigo' => 860, 'nombre' => 'Filial Maranatha - Isconcanta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Maranatha'],
            ['codigo' => 861, 'nombre' => 'Vichaya - Rosario', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Vichaya'],
            ['codigo' => 861, 'nombre' => 'Filial Rama Verde', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Rama Verde'],
            ['codigo' => 862, 'nombre' => 'Villa Esperanza', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Villa Esperanza'],
            ['codigo' => 862, 'nombre' => 'Filial Nueva Esmeralda', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. N. Esmeralda'],
            ['codigo' => 833, 'nombre' => 'Agua Rica - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Agua Rica'],
            ['codigo' => 834, 'nombre' => 'Calama - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Calama'],
            ['codigo' => 835, 'nombre' => 'Calasani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Calasani'],
            ['codigo' => 836, 'nombre' => 'Campero', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Campero'],
            ['codigo' => 837, 'nombre' => 'Condoriquiña', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Condoriquiña'],
            ['codigo' => 838, 'nombre' => 'El Arenal', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario El Arenal'],
            ['codigo' => 839, 'nombre' => 'Muruamaya - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Muruamaya'],
            ['codigo' => 840, 'nombre' => 'Playa Verde', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Playa Verde'],
            ['codigo' => 841, 'nombre' => 'Rosario', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Central'],
            ['codigo' => 621, 'nombre' => 'Japuma', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Japuma'],
            ['codigo' => 841, 'nombre' => 'Filial Anantoco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Anantoco'],
            ['codigo' => 841, 'nombre' => 'Filial Achavico', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Achavico'],
            ['codigo' => 841, 'nombre' => 'Filial Calacoto', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Calacoto'],
            ['codigo' => 841, 'nombre' => 'Filial Colina Blanca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Colina Blanca'],
            ['codigo' => 841, 'nombre' => 'Filial Lupirana', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario F. Lupirana'],
            ['codigo' => 842, 'nombre' => 'Viscachani - Rosario', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Rosario Viscachani'],
            ['codigo' => 860, 'nombre' => 'Sora Vilacollo', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Sora Vilacollo'],
            ['codigo' => 860, 'nombre' => 'Filial Playa Verde', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Playa Verde'],
            ['codigo' => 860, 'nombre' => 'Filial Tupaltupa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'F. Tupaltupa'],

            // Registros de Las Fronteras (ALTIPLANO)
            ['codigo' => 812, 'nombre' => 'CHARAÑA', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras CHARAÑA'],
            ['codigo' => 812, 'nombre' => 'Filial Berenguela', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Berenguela'],
            ['codigo' => 812, 'nombre' => 'Filial Tripartito', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Tripartito'],
            ['codigo' => 812, 'nombre' => 'Filial Collpacota', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Collpacota'],
            ['codigo' => 813, 'nombre' => 'Cosapa - Las Fronteras', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Fronteras Cosapa'],
            ['codigo' => 813, 'nombre' => 'Filial Rio Blanco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Fronteras F. Rio Blanco'],
            ['codigo' => 813, 'nombre' => 'Filial Sepultura', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Fronteras F. Sepultura'],
            ['codigo' => 814, 'nombre' => 'General Perez', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras CERRADO'],
            ['codigo' => 815, 'nombre' => 'Laguta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Laguta'],
            ['codigo' => 816, 'nombre' => 'Laram-Khota', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Laram-Khota'],
            ['codigo' => 817, 'nombre' => 'Mauri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Mauri'],
            ['codigo' => 817, 'nombre' => 'Filial Iñoca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Iñoca'],
            ['codigo' => 818, 'nombre' => 'Piedra Maravilla', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras P. Maravilla'],
            ['codigo' => 819, 'nombre' => 'Playa Vinto', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Playa Vinto'],
            ['codigo' => 820, 'nombre' => 'Sarcota', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Sarcota'],
            ['codigo' => 821, 'nombre' => 'Calasaya', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Calasaya'],
            ['codigo' => 822, 'nombre' => 'Cañahuyo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras C. Cerrado'],
            ['codigo' => 823, 'nombre' => 'Catacora', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Catacora'],
            ['codigo' => 824, 'nombre' => 'Chama', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Chama Central'],
            ['codigo' => 824, 'nombre' => 'Filial Pucjsani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Pucjsani'],
            ['codigo' => 824, 'nombre' => 'Filial Palestina', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Palestina'],
            ['codigo' => 824, 'nombre' => 'Filial Santo Domingo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. S. Domingo'],
            ['codigo' => 824, 'nombre' => 'Filial Sekopacuni', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Sekopacuni'],
            ['codigo' => 824, 'nombre' => 'Filial Sullcatito', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Sullcatito'],
            ['codigo' => 825, 'nombre' => 'Chama Baja - Las Fronteras', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Chama Baja'],
            ['codigo' => 826, 'nombre' => 'Chocorosi - Las Fronteras', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Chocorosi'],
            ['codigo' => 827, 'nombre' => 'Cuipa Alta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Cuipa Alta'],
            ['codigo' => 828, 'nombre' => 'Cuipa España', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Cuipa España'],
            ['codigo' => 828, 'nombre' => 'Filial Yawriri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras F. Yawriri'],
            ['codigo' => 829, 'nombre' => 'Laquinamaya', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Laquinamaya'],
            ['codigo' => 830, 'nombre' => 'Palomani', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Palomani'],
            ['codigo' => 831, 'nombre' => 'Santiago de Machaca', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'S. de Machaca Central'],
            ['codigo' => 831, 'nombre' => 'Filial Vila Willqui', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'S. de Machaca F. Vila W.'],
            ['codigo' => 831, 'nombre' => 'Filial Parachi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'S. de Machaca F. Parachi'],
            ['codigo' => 831, 'nombre' => 'Filial Añufani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'S. de Machaca F. Añufani'],
            ['codigo' => 832, 'nombre' => 'Thola Kollo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Fronteras Thola Kollo'],

            // Registros de Curahuara (ALTIPLANO, ORURO/LA PAZ)
            ['codigo' => 618, 'nombre' => 'Curahuara', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Central'],
            ['codigo' => 619, 'nombre' => 'Huacanapi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Huacanapi'],
            ['codigo' => 620, 'nombre' => 'Janco Jayuni', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Janco J.'],
            ['codigo' => 621, 'nombre' => 'Filial Limari', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Limari'],
            ['codigo' => 621, 'nombre' => 'Filial Nueva Alianza', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. N. Alianza'],
            ['codigo' => 622, 'nombre' => 'Lerco', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Lerco'],
            ['codigo' => 622, 'nombre' => 'Filial Calasaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Calasaya'],
            ['codigo' => 623, 'nombre' => 'San Pedro de Totora', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'S. P. de Totora Central'],
            ['codigo' => 623, 'nombre' => 'Filial Irpajoco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'S. P. de Totora F. Irp.'],
            ['codigo' => 623, 'nombre' => 'Filial Chojñacota', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'S. P. de Totora F. Choj.'],
            ['codigo' => 623, 'nombre' => 'Filial Crucero', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'S. P. de Totora F. Cru.'],
            ['codigo' => 624, 'nombre' => 'Sora Sora - Curahuara', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Sora Sora'],
            ['codigo' => 624, 'nombre' => 'Filial Culta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Culta'],
            ['codigo' => 625, 'nombre' => 'Ulloma', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Ulloma Central'],
            ['codigo' => 625, 'nombre' => 'Filial Cerro Totocachi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Ulloma F. C. Totocachi'],
            ['codigo' => 625, 'nombre' => 'Filial Chaqueña', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Ulloma F. Chaqueña'],
            ['codigo' => 626, 'nombre' => 'Villa Libertad', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Villa Libertad'],
            ['codigo' => 626, 'nombre' => 'Filial Luquipi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'V. Libertad F. Luquipi'],
            ['codigo' => 627, 'nombre' => 'Caripe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Caripe'],
            ['codigo' => 627, 'nombre' => 'Filial Choquemarca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Choquemarca'],
            ['codigo' => 627, 'nombre' => 'Filial Jerusalem', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Jerusalem'],
            ['codigo' => 628, 'nombre' => 'Cosapa - Curahuara', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Cosapa Curahuara'],
            ['codigo' => 628, 'nombre' => 'Filial Turco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Cosapa F. Turco'],
            ['codigo' => 629, 'nombre' => 'Plazuela - Curahuara', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Plazuela'],
            ['codigo' => 630, 'nombre' => 'Sajama - Curahuara', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Sajama'],
            ['codigo' => 630, 'nombre' => 'Filial Laguna', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Laguna'],
            ['codigo' => 630, 'nombre' => 'Filial Casilla', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Casilla'],
            ['codigo' => 631, 'nombre' => 'Vilacollo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara Vilacollo'],
            ['codigo' => 631, 'nombre' => 'Filial Tikapampa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Tikapampa'],
            ['codigo' => 631, 'nombre' => 'Filial Chocohuta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Curahuara F. Chocohuta'],

            // Registros de Lahuachaca (ALTIPLANO, LA PAZ)
            ['codigo' => 668, 'nombre' => 'Ampicolque', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Ampicolque'],
            ['codigo' => 668, 'nombre' => 'Filial Iracachi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Iracachi'],
            ['codigo' => 669, 'nombre' => 'Belén - Lahuachaca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Belén'],
            ['codigo' => 669, 'nombre' => 'Filial Huanocollo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Huanocollo'],
            ['codigo' => 669, 'nombre' => 'Filial Belen de palestina', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Belén P.'],
            ['codigo' => 669, 'nombre' => 'Filial Catavi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Catavi'],
            ['codigo' => 669, 'nombre' => 'Filial Buen Samaritano', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. B. Samaritano'],
            ['codigo' => 670, 'nombre' => 'Canal de Luz', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Canal de Luz'],
            ['codigo' => 671, 'nombre' => 'Collpa', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Collpa'],
            ['codigo' => 672, 'nombre' => 'Franz Tamayo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Franz Tamayo'],
            ['codigo' => 672, 'nombre' => 'Filial Iripe', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Iripe'],
            ['codigo' => 673, 'nombre' => 'Huaraco', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Huaraco'],
            ['codigo' => 673, 'nombre' => 'Filial Ojtaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Ojtaya'],
            ['codigo' => 673, 'nombre' => 'Filial Vila Vila', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Vila Vila'],
            ['codigo' => 673, 'nombre' => 'Filial Aparuri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Aparuri'],
            ['codigo' => 673, 'nombre' => 'Filial Toloma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Toloma'],
            ['codigo' => 674, 'nombre' => 'Huntuta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Huntuta'],
            ['codigo' => 674, 'nombre' => 'Filial Challoma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Challoma'],
            ['codigo' => 674, 'nombre' => 'Filial Konchamarka', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Konchamarka'],
            ['codigo' => 675, 'nombre' => 'Ichoca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Ichoca'],
            ['codigo' => 676, 'nombre' => 'Jupiri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Jupiri'],
            ['codigo' => 676, 'nombre' => 'Filial Puchuni', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Puchuni'],
            ['codigo' => 677, 'nombre' => 'Konani', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Konani'],
            ['codigo' => 678, 'nombre' => 'Lahuachaca', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Central'],
            ['codigo' => 679, 'nombre' => 'Pacollo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Pacollo'],
            ['codigo' => 680, 'nombre' => 'Pampahasi - Lahuachaca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Pampahasi'],
            ['codigo' => 681, 'nombre' => 'Sica Sica', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Sica Sica'],
            ['codigo' => 682, 'nombre' => 'Tablachaca', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Tablachaca'],
            ['codigo' => 682, 'nombre' => 'Filial Iquilluyo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Iquilluyo'],
            ['codigo' => 682, 'nombre' => 'Filial Mecaña', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Mecaña'],
            ['codigo' => 682, 'nombre' => 'Filial Caxata', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Caxata'],
            ['codigo' => 682, 'nombre' => 'Filial Llipi llipi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca F. Llipi llipi'],
            ['codigo' => 683, 'nombre' => 'Vilaque', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Lahuachaca Vilaque'],

            // Registros de Patacamaya (ALTIPLANO, LA PAZ)
            ['codigo' => 684, 'nombre' => 'Cauchititiri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Cauchititiri'],
            ['codigo' => 685, 'nombre' => 'Huari Belén', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Huari Belén'],
            ['codigo' => 685, 'nombre' => 'Filial GP Chapicollo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chapicollo'],
            ['codigo' => 685, 'nombre' => 'Filial copani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Copani'],
            ['codigo' => 686, 'nombre' => 'Llanga Belén', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Llanga Belén'],
            ['codigo' => 686, 'nombre' => 'Filial San Juan Circa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. San Juan C.'],
            ['codigo' => 687, 'nombre' => 'Patacamaya Central', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Central'],
            ['codigo' => 687, 'nombre' => 'Filial Anchallani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Anchallani'],
            ['codigo' => 687, 'nombre' => 'Filial Cultani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Cultani'],
            ['codigo' => 687, 'nombre' => 'Filial Maranatha', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Maranatha'],
            ['codigo' => 687, 'nombre' => 'Filial San Juan Culta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. San Juan Culta'],
            ['codigo' => 687, 'nombre' => 'Filial calteca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Calteca'],
            ['codigo' => 688, 'nombre' => 'Sallacirca', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Sallacirca'],
            ['codigo' => 688, 'nombre' => 'Filial Iramaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Iramaya'],
            ['codigo' => 689, 'nombre' => 'San José - Patacamaya "A"', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya San José A'],
            ['codigo' => 690, 'nombre' => 'Santiago de Collana', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya S. de Collana'],
            ['codigo' => 691, 'nombre' => 'Shalom', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Shalom'],
            ['codigo' => 691, 'nombre' => 'Filial Chacoma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chacoma'],
            ['codigo' => 691, 'nombre' => 'Filial Hiscacollo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Hiscacollo'],
            ['codigo' => 692, 'nombre' => 'Sora Sora - Patacamaya "A"', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Sora Sora A'],
            ['codigo' => 692, 'nombre' => 'Filial Chijmuni', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chijmuni'],
            ['codigo' => 693, 'nombre' => 'Toloma', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Toloma'],
            ['codigo' => 693, 'nombre' => 'Filial Cañaviri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Cañaviri'],
            ['codigo' => 693, 'nombre' => 'Filial Yahurichambi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Yahurichambi'],
            ['codigo' => 693, 'nombre' => 'Filial Chancahuayto', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chancahuayto'],

            // Registros de Patacamaya "B" y Áreas Circundantes (ALTIPLANO, LA PAZ)
            ['codigo' => 883, 'nombre' => 'Advenir', 'tipo' => 'Grupo', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'Advenir'], // Se asume en El Alto por el nombre y la filial.
            ['codigo' => 883, 'nombre' => 'Filial Villa Ingenio', 'tipo' => 'Filial', 'lugar' => 'EL ALTO', 'ciudad' => 'La Paz', 'zona' => 'F. Villa Ingenio'],
            ['codigo' => 694, 'nombre' => 'Cacha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Cacha'],
            ['codigo' => 694, 'nombre' => 'Filial Chillcani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chillcani'],
            ['codigo' => 694, 'nombre' => 'Filial Corhua', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Corhua'],
            ['codigo' => 694, 'nombre' => 'Filial Muruhuta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Muruhuta'],
            ['codigo' => 695, 'nombre' => 'Capunuta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Capunuta'],
            ['codigo' => 696, 'nombre' => 'Challapata', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Challapata'],
            ['codigo' => 697, 'nombre' => 'Chiarumani', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Chiarumani'],
            ['codigo' => 697, 'nombre' => 'Filial Monte Calvario', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Monte C.'],
            ['codigo' => 697, 'nombre' => 'Filial Muruchapi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Muruchapi'],
            ['codigo' => 697, 'nombre' => 'Filial Machac Huyo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Machac H.'],
            ['codigo' => 697, 'nombre' => 'Filial Villa Quishuarani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Villa Q.'],
            ['codigo' => 698, 'nombre' => 'El Porvenir', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya El Porvenir'],
            ['codigo' => 699, 'nombre' => 'Hisca - Hoco', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Hisca - Hoco'],
            ['codigo' => 699, 'nombre' => 'Filial Nueva Esperanza', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. N. Esperanza'],
            ['codigo' => 699, 'nombre' => 'Filial Taracollo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Taracollo'],
            ['codigo' => 699, 'nombre' => 'Filial Chojllacota', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chojllacota'],
            ['codigo' => 699, 'nombre' => 'Filial Pomposillo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Pomposillo'],
            ['codigo' => 700, 'nombre' => 'Humatoma', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Humatoma'],
            ['codigo' => 700, 'nombre' => 'Filial Cumbre Vilacota', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. C. Vilacota'],
            ['codigo' => 700, 'nombre' => 'Filial Irutira', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Irutira'],
            ['codigo' => 700, 'nombre' => 'Filial Centro Araca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. C. Araca'],
            ['codigo' => 701, 'nombre' => 'Laguna Blanca', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Laguna Blanca'],
            ['codigo' => 701, 'nombre' => 'Filial Puerto Aroma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. P. Aroma'],
            ['codigo' => 701, 'nombre' => 'Filial Chusicani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Chusicani'],
            ['codigo' => 702, 'nombre' => 'Mantecani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Mantecani'],
            ['codigo' => 703, 'nombre' => 'Patarani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Patarani'],
            ['codigo' => 704, 'nombre' => 'Puchuni', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Puchuni'],
            ['codigo' => 705, 'nombre' => 'Tolar', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Tolar'],
            ['codigo' => 706, 'nombre' => 'Viscachani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Viscachani'],
            ['codigo' => 706, 'nombre' => 'Filial Ayo Ayo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Ayo Ayo'],
            ['codigo' => 706, 'nombre' => 'Filial Collpacanta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Collpacanta'],
            ['codigo' => 706, 'nombre' => 'Filial San Martin de Iquiaca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. S. M. Iquiaca'],
            ['codigo' => 707, 'nombre' => 'Achaviri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Achaviri'],
            ['codigo' => 707, 'nombre' => 'Filial Manquiri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Manquiri'],
            ['codigo' => 708, 'nombre' => 'Acohaconi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Acohaconi'],
            ['codigo' => 708, 'nombre' => 'Filial San Pedro de Curahuara', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'Oruro', 'zona' => 'Patacamaya F. S. P. Curahuara'],
            ['codigo' => 709, 'nombre' => 'Chapicollo - Patihipe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Chapicollo'],
            ['codigo' => 710, 'nombre' => 'Chojña A', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Chojña A'],
            ['codigo' => 710, 'nombre' => 'Filial Cotapata', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya F. Cotapata'],
            ['codigo' => 711, 'nombre' => 'Chojña B', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Chojña B'],
            ['codigo' => 712, 'nombre' => 'Escalona', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patacamaya Escalona'],
            //bloque 3


            ['codigo' => 712, 'nombre' => 'Filial Union Tolar', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. U. Tolar'],
            ['codigo' => 712, 'nombre' => 'Filial Bolivar', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Bolívar'],
            ['codigo' => 713, 'nombre' => 'Hornuni', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Hornuni'],
            ['codigo' => 714, 'nombre' => 'Jalsuri - Patihipe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Jalsuri'],
            ['codigo' => 715, 'nombre' => 'Llicapani', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Llicapani'],
            ['codigo' => 715, 'nombre' => 'Filial Pacollo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Pacollo'],
            ['codigo' => 716, 'nombre' => 'Luquiamaya', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Luquiamaya'],
            ['codigo' => 717, 'nombre' => 'Machacamarca - Patihipe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Machacamarca'],
            ['codigo' => 718, 'nombre' => 'Mariscal Santa Cruz - Patihipe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe M. S. Cruz'],
            ['codigo' => 719, 'nombre' => 'Mollebamba', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Mollebamba'],
            ['codigo' => 720, 'nombre' => 'Ñequejawira', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Ñequejawira'],
            ['codigo' => 721, 'nombre' => 'Patihipi', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Central'],
            ['codigo' => 721, 'nombre' => 'Filial Hiruyo', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Hiruyo'],
            ['codigo' => 721, 'nombre' => 'Filial Tolahuancarama', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Tolahuancarama'],
            ['codigo' => 722, 'nombre' => 'Villa Esperanza - Patihipe', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Villa Esperanza'],
            ['codigo' => 723, 'nombre' => 'Villa Pampa', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe Villa Pampa'],
            ['codigo' => 723, 'nombre' => 'Filial Kari', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Kari'],
            ['codigo' => 723, 'nombre' => 'Filial Bella Vista', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Patihipe F. Bella Vista'],

            // Registros de El Valle / Sapahaqui (ALTIPLANO/VALLE, LA PAZ)
            ['codigo' => 632, 'nombre' => 'Agua Salud', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Agua Salud'],
            ['codigo' => 632, 'nombre' => 'Filial Kara', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Kara'],
            ['codigo' => 633, 'nombre' => 'Anquioma', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Anquioma'],
            ['codigo' => 633, 'nombre' => 'Filial Aukamarka', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Aukamarka'],
            ['codigo' => 634, 'nombre' => 'Ayna', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Ayna'],
            ['codigo' => 647, 'nombre' => 'Ayru Irama', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Ayru Irama'],
            ['codigo' => 647, 'nombre' => 'Filial Suquy', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Suquy'],
            ['codigo' => 635, 'nombre' => 'Azambo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Azambo'],
            ['codigo' => 635, 'nombre' => 'Filial Matara-chirimaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Matara-chir.'],
            ['codigo' => 636, 'nombre' => 'Cachualla', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Cachualla'],
            ['codigo' => 636, 'nombre' => 'Filial Cuty', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Cuty'],
            ['codigo' => 636, 'nombre' => 'Filial Collpani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Collpani'],
            ['codigo' => 637, 'nombre' => 'Candial', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Candial'],
            ['codigo' => 638, 'nombre' => 'Caracato', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Caracato'],
            ['codigo' => 639, 'nombre' => 'Carayapu', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Carayapu'],
            ['codigo' => 640, 'nombre' => 'Cebollar', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Cebollar'],
            ['codigo' => 641, 'nombre' => 'Chincha', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Chincha'],
            ['codigo' => 641, 'nombre' => 'Filial Choquesa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Choquesa'],
            ['codigo' => 642, 'nombre' => 'Chivisivi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Chivisivi'],
            ['codigo' => 643, 'nombre' => 'Huayhuasi - El Valle', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Huayhuasi'],
            ['codigo' => 644, 'nombre' => 'Jachapampa', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Jachapampa'],
            ['codigo' => 644, 'nombre' => 'Filial Jachapampa II', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Jachapampa II'],
            ['codigo' => 645, 'nombre' => 'Khola', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Khola'],
            ['codigo' => 646, 'nombre' => 'Lacaya', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Lacaya'],
            ['codigo' => 646, 'nombre' => 'Filial Ocuire', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Ocuire'],
            ['codigo' => 648, 'nombre' => 'Molino Pata', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Molino Pata'],
            ['codigo' => 650, 'nombre' => 'Sapahaqui', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Sapahaqui Central'],
            ['codigo' => 651, 'nombre' => 'Sixilla Alta', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Sapahaqui Sixilla Alta'],
            ['codigo' => 652, 'nombre' => 'Keraya', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Keraya'],
            ['codigo' => 649, 'nombre' => 'Quebrada', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Quebrada'],
            ['codigo' => 653, 'nombre' => 'Pucarani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Pucarani'],
            ['codigo' => 653, 'nombre' => 'GP Jañumarca', 'tipo' => 'filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle F. Jañumarca'],
            ['codigo' => 890, 'nombre' => 'Tirco', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'El Valle Tirco'],

            // Registros de Viloco / Inquisivi (ALTIPLANO/VALLE, LA PAZ)
            ['codigo' => 654, 'nombre' => 'Filial Wilapampa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Wilapampa'],
            ['codigo' => 654, 'nombre' => 'Viloco', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco Central'],
            ['codigo' => 654, 'nombre' => 'Filial Atoroma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Atoroma'],
            ['codigo' => 654, 'nombre' => 'Filial Cairoma', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Cairoma'],
            ['codigo' => 654, 'nombre' => 'Filial Colcani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Colcani'],
            ['codigo' => 654, 'nombre' => 'Filial Humaruta', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Humaruta'],
            ['codigo' => 654, 'nombre' => 'Filial La Lloja', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. La Lloja'],
            ['codigo' => 654, 'nombre' => 'Filial Saya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Saya'],
            ['codigo' => 654, 'nombre' => 'Filial Sumiraya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Viloco F. Sumiraya'],
            ['codigo' => 655, 'nombre' => 'Acutani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Acutani'],
            ['codigo' => 656, 'nombre' => 'Canqui Centro', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Canqui C.'],
            ['codigo' => 657, 'nombre' => 'Canqui Chico', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Canqui Ch.'],
            ['codigo' => 658, 'nombre' => 'Capiñata', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Capiñata'],
            ['codigo' => 658, 'nombre' => 'Filial Chiji', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Chiji'],
            ['codigo' => 658, 'nombre' => 'Filial Tiquipacha', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Tiquipacha'],
            ['codigo' => 659, 'nombre' => 'Chorocona', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Chorocona'],
            ['codigo' => 885, 'nombre' => 'Cochabambita', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Cochabambita'],
            ['codigo' => 660, 'nombre' => 'Corachapi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Corachapi'],
            ['codigo' => 661, 'nombre' => 'Inquisivi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Central'],
            ['codigo' => 662, 'nombre' => 'Locotani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Locotani'],
            ['codigo' => 662, 'nombre' => 'Filial Minas', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Minas'],
            ['codigo' => 663, 'nombre' => 'Munaypata - Inquisivi', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Munaypata'],
            ['codigo' => 663, 'nombre' => 'Filial Copacabana', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Copacabana'],
            ['codigo' => 663, 'nombre' => 'Filial Cosco', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Cosco'],
            ['codigo' => 664, 'nombre' => 'Pinoloma', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Pinoloma'],
            ['codigo' => 665, 'nombre' => 'Quime', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Quime'],
            ['codigo' => 665, 'nombre' => 'Filial Calazaya', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Calazaya'],
            ['codigo' => 884, 'nombre' => 'Sita', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Sita'],
            ['codigo' => 666, 'nombre' => 'Vilacota', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Vilacota'],
            ['codigo' => 667, 'nombre' => 'Yacupampa', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi Yacupampa'],
            ['codigo' => 667, 'nombre' => 'Filial Laca Laca', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Inquisivi F. Laca Laca'],

            // Registros de Cajuata / Miguillas (ALTIPLANO/VALLE, LA PAZ)
            ['codigo' => 600, 'nombre' => 'Agua Rica - Cajuata', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Agua Rica'],
            ['codigo' => 600, 'nombre' => 'Filial Polea', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Polea'],
            ['codigo' => 601, 'nombre' => 'Cajuata', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Central'],
            ['codigo' => 602, 'nombre' => 'Cañamina', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Cañamina'],
            ['codigo' => 603, 'nombre' => 'Chajna', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Chajna'],
            ['codigo' => 604, 'nombre' => 'Challviri', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Challviri'],
            ['codigo' => 604, 'nombre' => 'Filial Ventilla', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Ventilla'],
            ['codigo' => 604, 'nombre' => 'Filial Frutillani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Frutillani'],
            ['codigo' => 605, 'nombre' => 'Cheka', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Cheka'],
            ['codigo' => 606, 'nombre' => 'Chillcani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Chillcani'],
            ['codigo' => 607, 'nombre' => 'Circuata', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Circuata'],
            ['codigo' => 888, 'nombre' => 'Huaritolo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Huaritolo'],
            ['codigo' => 608, 'nombre' => 'Licoma', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Licoma'],
            ['codigo' => 608, 'nombre' => 'Filial Palomani', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Palomani'],
            ['codigo' => 608, 'nombre' => 'Filial Suri', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Suri'],
            ['codigo' => 608, 'nombre' => 'Filial Santa Rosa', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Santa Rosa'],
            ['codigo' => 609, 'nombre' => 'Loma Linda', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Loma Linda'],
            ['codigo' => 609, 'nombre' => 'Filial Turculi', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Turculi'],
            ['codigo' => 887, 'nombre' => 'Lujmani', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Lujmani'],
            ['codigo' => 610, 'nombre' => 'Miguillas', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Miguillas Central'],
            ['codigo' => 611, 'nombre' => 'Moxacoca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Miguillas Moxacoca'],
            ['codigo' => 611, 'nombre' => 'Filial Parpata', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Miguillas F. Parpata'],
            ['codigo' => 612, 'nombre' => 'Siquimirami', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Siquimirami'],
            ['codigo' => 613, 'nombre' => 'Sojetaca', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Sojetaca'],
            ['codigo' => 614, 'nombre' => 'Suticollo', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Suticollo'],
            ['codigo' => 615, 'nombre' => 'Villa Angélica', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Villa Angélica'],
            ['codigo' => 616, 'nombre' => 'Villa Barrientos', 'tipo' => 'Iglesia', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Villa Barrientos'],
            ['codigo' => 617, 'nombre' => 'Villa Khora', 'tipo' => 'Grupo', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata Villa Khora'],
            ['codigo' => 617, 'nombre' => 'Filial Viscachala', 'tipo' => 'Filial', 'lugar' => 'ALTIPLANO', 'ciudad' => 'La Paz', 'zona' => 'Cajuata F. Viscachala'],
        ];

        // Mapear los datos para la inserción
        // Insertar todas las iglesias de una sola vez
        DB::table('iglesias')->insert($datosIglesias);

    }
}
