<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // <<<<< Esto es lo que falta
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;
class PersonaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('personas')->insert([
            'nombre' => 'Eddy',
                'ape_paterno' => 'Mamani',
                'ape_materno' => 'Condori',
                'fecha_nac' => '1997-04-19',
                'ci' => '12892618 LP',
                'celular' => 63072384,
                'ciudad' => 'Tarija',
                'zona' => 'San Roque',
                'calle' => 'Colon',
                'nro' => '8',
                'email' => 'eddyuser@mbos.com',
                'password' => Hash::make('eddypassword123'),
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        ]);

            DB::table('personas')->insert([
                'nombre' => 'Franklin',
                    'ape_paterno' => 'Mamani',
                    'ape_materno' => 'Mamani',
                    'fecha_nac' => '1997-04-19',
                    'ci' => '77382643',
                    'celular' => 76543217,
                    'ciudad' => 'La Paz',
                    'zona' => 'Villa Exaltacion',
                    'calle' => '23',
                    'nro' => '8',
                    'email' => 'franklinuser@mbos.com',
                    'password' => Hash::make('franklinpassword123'),
                    'estado' => true,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
            ]);
            
        $personas = [
        [
            'ape_paterno' => 'Aguilar',
            'ape_materno' => 'Conde',
            'nombre' => 'Emmanuel',
            'fecha_nac' => '1992-10-16',
            'ci' => '10387002 Chuq.',
            'email' => 'emmanueluser@mbos.com',
            'password' => Hash::make('emmanuelpassword123'),
            'foto_perfil' => 'perfiles/emmanuel_aguilar.jpg',
        ],
        [
            'ape_paterno' => 'Aliaga',
            'ape_materno' => 'Quispe',
            'nombre' => 'Fidel',
            'fecha_nac' => '1977-04-24',
            'ci' => '4843050 LP',
            'email' => 'fideluser@mbos.com',
            'password' => Hash::make('fidelpassword123'),
            'foto_perfil' => 'perfiles/fidel_aliaga.jpg',
        ],
        [
            'ape_paterno' => 'Apaza',
            'ape_materno' => 'Quiñones',
            'nombre' => 'Hugo',
            'fecha_nac' => '1990-10-03',
            'ci' => '6915986 LP.',
            'email' => 'hugouser@mbos.com',
            'password' => Hash::make('hugopassword123'),
            'foto_perfil' => 'perfiles/hugo_apaza.jpg',
        ],
        [
            'ape_paterno' => 'Bautista',
            'ape_materno' => 'Calle',
            'nombre' => 'Miguel Ángel',
            'fecha_nac' => '1994-06-19',
            'ci' => '7020616 LP',
            'email' => 'miguelangeluser@mbos.com',
            'password' => Hash::make('miguelangelpassword123'),
            'foto_perfil' => 'perfiles/miguel_bautista.jpg',
        ],
        [
            'ape_paterno' => 'Chambi',
            'ape_materno' => 'Catunta',
            'nombre' => 'Wilmer Elio',
            'fecha_nac' => '1994-12-16',
            'ci' => '9963954 LP.',
            'email' => 'wilmeruser@mbos.com',
            'password' => Hash::make('wilmerpassword123'),
            'foto_perfil' => 'perfiles/wilmer_chambi.jpg',
        ],
        [
            'ape_paterno' => 'Chambilla',
            'ape_materno' => 'Esprella',
            'nombre' => 'Rubén',
            'fecha_nac' => '1987-04-01',
            'ci' => '6768769 LP.',
            'email' => 'rubenuser@mbos.com',
            'password' => Hash::make('rubenpassword123'),
            'foto_perfil' => 'perfiles/ruben_chambilla.jpg',
        ],
        [
            'ape_paterno' => 'Chino',
            'ape_materno' => 'Chipana',
            'nombre' => 'John',
            'fecha_nac' => '1970-01-01',
            'ci' => '3424647 LP.',
            'email' => 'jhonuser@mbos.com',
            'password' => Hash::make('jhonsword123'),
            'foto_perfil' => 'perfiles/john_chino.jpg',
        ],
        [
            'ape_paterno' => 'Chipana',
            'ape_materno' => 'Serrano',
            'nombre' => 'Mauro',
            'fecha_nac' => '1982-08-19',
            'ci' => '6089115 LP.',
            'email' => 'maurouser@mbos.com',
            'password' => Hash::make('mauropassword123'),
            'foto_perfil' => 'perfiles/mauro_chipana.jpg',
        ],
        [
            'ape_paterno' => 'Chuquimia',
            'ape_materno' => 'Lucana',
            'nombre' => 'Robie',
            'fecha_nac' => '1997-09-02',
            'ci' => '10805636 BN',
            'email' => 'robieuser@mbos.com',
            'password' => Hash::make('robiepassword123'),
            'foto_perfil' => 'perfiles/robie_chuquimia.jpg',
        ],
        [
            'ape_paterno' => 'Condori',
            'ape_materno' => 'Canaviri',
            'nombre' => 'Alvaro Gabriel',
            'fecha_nac' => '1988-05-21',
            'ci' => '6853028 LP',
            'email' => 'alvarogabrieluser@mbos.com',
            'password' => Hash::make('alvarogabrielpassword123'),
            'foto_perfil' => 'perfiles/alvaro_condori.jpg',
        ],
        [
            'ape_paterno' => 'Coronel',
            'ape_materno' => 'Laime',
            'nombre' => 'Henry Wilson',
            'fecha_nac' => '1976-10-31',
            'ci' => '4800042 LP.',
            'email' => 'henrywilsonuser@mbos.com',
            'password' => Hash::make('henrywilsonpassword123'),
            'foto_perfil' => 'perfiles/henry_coronel.jpg',
        ],
        [
            'ape_paterno' => 'Escarzo',
            'ape_materno' => 'Nina',
            'nombre' => 'José Edwin',
            'fecha_nac' => '1978-12-27',
            'ci' => '4046655 OR.',
            'email' => 'joseedwinuser@mbos.com',
            'password' => Hash::make('joseedwinpassword123'),
            'foto_perfil' => 'perfiles/jose_escarzo.jpg',
        ],
        [
            'ape_paterno' => 'Gutierrez',
            'ape_materno' => 'Limachi',
            'nombre' => 'David',
            'fecha_nac' => '1983-09-13',
            'ci' => '4774964 LP.',
            'email' => 'daviduser@mbos.com',
            'password' => Hash::make('davidpassword123'),
            'foto_perfil' => 'perfiles/david_gutierrez.jpg',
        ],
        [
            'ape_paterno' => 'Larico',
            'ape_materno' => 'Aruquipa',
            'nombre' => 'Noel',
            'fecha_nac' => '1987-05-01',
            'ci' => '6188628 LP.',
            'email' => 'noeluser@mbos.com',
            'password' => Hash::make('noelpassword123'),
            'foto_perfil' => 'perfiles/noel_larico.jpg',
        ],
        [
            'ape_paterno' => 'Lima',
            'ape_materno' => 'Huanca',
            'nombre' => 'Juan Carlos',
            'fecha_nac' => '1989-05-16',
            'ci' => '5033881 Tja.',
            'email' => 'juancarlosuser@mbos.com',
            'password' => Hash::make('juancarlospassword123'),
            'foto_perfil' => 'perfiles/juan_lima.jpg',
        ],
        [
            'ape_paterno' => 'Llanos',
            'ape_materno' => 'Cohaila',
            'nombre' => 'Adhemar',
            'fecha_nac' => '1997-10-26',
            'ci' => '12449941-LP',
            'email' => 'adhemaruser@mbos.com',
            'password' => Hash::make('adhemarpassword123'),
            'foto_perfil' => 'perfiles/adhemar_llanos.jpg',
        ],
        [
            'ape_paterno' => 'Llanos',
            'ape_materno' => 'Cohaila',
            'nombre' => 'Omar',
            'fecha_nac' => '1989-12-23',
            'ci' => '8304655 LP',
            'email' => 'omaruser@mbos.com',
            'password' => Hash::make('omarpassword123'),
            'foto_perfil' => 'perfiles/omar_llanos.jpg',
        ],
        [
            'ape_paterno' => 'Llusco',
            'ape_materno' => 'Chavez',
            'nombre' => 'Edson Plinio',
            'fecha_nac' => '1989-03-25',
            'ci' => '6890587 LP',
            'email' => 'edsonpliniouser@mbos.com',
            'password' => Hash::make('edsonpliniopassword123'),
            'foto_perfil' => 'perfiles/edson_llusco.jpg',
        ],
        [
            'ape_paterno' => 'Mamani',
            'ape_materno' => 'Limachi',
            'nombre' => 'Fidel John',
            'fecha_nac' => '1971-05-24',
            'ci' => '3478403 CBB.',
            'email' => 'fideljhonuser@mbos.com',
            'password' => Hash::make('fideljhonpassword123'),
            'foto_perfil' => 'perfiles/fidel_mamani.jpg',
        ],
        [
            'ape_paterno' => 'Mamani',
            'ape_materno' => 'Mamani',
            'nombre' => 'Sergio',
            'fecha_nac' => '1987-05-11',
            'ci' => '7005521 LP.',
            'email' => 'sergiouser@mbos.com',
            'password' => Hash::make('sergiopassword123'),
            'foto_perfil' => 'perfiles/sergio_mamani.jpg',
        ],
        [
            'ape_paterno' => 'Mena',
            'ape_materno' => 'Laura',
            'nombre' => 'Benjamín Josué',
            'fecha_nac' => '1998-04-25',
            'ci' => '12449941 LP',
            'email' => 'benjaminjosueuser@mbos.com',
            'password' => Hash::make('benjaminjosuepassword123'),
            'foto_perfil' => 'perfiles/benjamin_mena.jpg',
        ],
        [
            'ape_paterno' => 'Morante',
            'ape_materno' => 'Kondori',
            'nombre' => 'Manuel Huascar',
            'fecha_nac' => '1970-09-22',
            'ci' => '3434083 LP.',
            'email' => 'manualhuascaruser@mbos.com',
            'password' => Hash::make('manualhuascarpassword123'),
            'foto_perfil' => 'perfiles/manuel_morante.jpg',
        ],
        [
            'ape_paterno' => 'Moya',
            'ape_materno' => 'Condori',
            'nombre' => 'Ronald',
            'fecha_nac' => '1987-11-30',
            'ci' => '6955431 LP.',
            'email' => 'ronalduser@mbos.com',
            'password' => Hash::make('ronaldpassword123'),
            'foto_perfil' => 'perfiles/ronald_moya.jpg',
        ],
        [
            'ape_paterno' => 'Pairo',
            'ape_materno' => 'Mamani',
            'nombre' => 'Ever',
            'fecha_nac' => '1995-12-15',
            'ci' => '10062204 LP.',
            'email' => 'everuser@mbos.com',
            'password' => Hash::make('everpassword123'),
            'foto_perfil' => 'perfiles/ever_pairo.jpg',
        ],
        [
            'ape_paterno' => 'Pari',
            'ape_materno' => 'Tipo',
            'nombre' => 'Mequías',
            'fecha_nac' => '1982-07-26',
            'ci' => '6178853 LP.',
            'email' => 'mequiasuser@mbos.com',
            'password' => Hash::make('mequiaspassword123'),
            'foto_perfil' => 'perfiles/mequias_pari.jpg',
        ],
        [
            'ape_paterno' => 'Pinto',
            'ape_materno' => 'Salvatierra',
            'nombre' => 'Mario Carlos',
            'fecha_nac' => '1976-12-20',
            'ci' => '4834871 LP.',
            'email' => 'mariocarlosuser@mbos.com',
            'password' => Hash::make('mariocarlospassword123'),
            'foto_perfil' => 'perfiles/mario_pinto.jpg',
        ],
        [
            'ape_paterno' => 'Pomacusi',
            'ape_materno' => 'Cari',
            'nombre' => 'Mario Alejandro',
            'fecha_nac' => '1994-06-19',
            'ci' => '8354769 LP.',
            'email' => 'marioalejandrouser@mbos.com',
            'password' => Hash::make('marioalejandropassword123'),
            'foto_perfil' => 'perfiles/mario_pomacusi.jpg',
        ],
        [
            'ape_paterno' => 'Quipildor',
            'ape_materno' => 'Tito',
            'nombre' => 'Juan Luis',
            'fecha_nac' => '1964-01-21',
            'ci' => '2621402 LP.',
            'email' => 'juanluisuser@mbos.com',
            'password' => Hash::make('juanluispassword123'),
            'foto_perfil' => 'perfiles/juan_quipildor.jpg',
        ],
        [
            'ape_paterno' => 'Quispe',
            'ape_materno' => 'Sánchez',
            'nombre' => 'Josué',
            'fecha_nac' => '1994-07-26',
            'ci' => '8404262 LP',
            'email' => 'josueuser@mbos.com',
            'password' => Hash::make('josuepassword123'),
            'foto_perfil' => 'perfiles/josue_quispe.jpg',
        ],
        [
            'ape_paterno' => 'Quispe',
            'ape_materno' => 'Espinoza',
            'nombre' => 'Juan Eusebio',
            'fecha_nac' => '1988-12-07',
            'ci' => '7055964 LP.',
            'email' => 'juaneusebiouser@mbos.com',
            'password' => Hash::make('juaneusebiopassword123'),
            'foto_perfil' => 'perfiles/juan_quispe.jpg',
        ],
        [
            'ape_paterno' => 'Quiuchaca',
            'ape_materno' => 'Apaza',
            'nombre' => 'Nelo',
            'fecha_nac' => '1993-05-05',
            'ci' => '8439312 LP.',
            'email' => 'nelouser@mbos.com',
            'password' => Hash::make('nelopassword123'),
            'foto_perfil' => 'perfiles/nelo_quiuchaca.jpg',
        ],
        [
            'ape_paterno' => 'Sajama',
            'ape_materno' => 'Sánchez',
            'nombre' => 'David',
            'fecha_nac' => '1993-04-15',
            'ci' => '7278224 OR.',
            'email' => 'davidsanchezuser@mbos.com',
            'password' => Hash::make('davidsanchezpassword123'),
            'foto_perfil' => 'perfiles/david_sajama.jpg',
        ],
        [
            'ape_paterno' => 'Sirpa',
            'ape_materno' => 'Alcon',
            'nombre' => 'Juan Milton',
            'fecha_nac' => '1989-10-03',
            'ci' => '7037306 LP.',
            'email' => 'juanmiltonuser@mbos.com',
            'password' => Hash::make('juanmiltonpassword123'),
            'foto_perfil' => 'perfiles/juan_sirpa.jpg',
        ],
        [
            'ape_paterno' => 'Tapia',
            'ape_materno' => 'Muñoz',
            'nombre' => 'Nelson',
            'fecha_nac' => '1984-11-22',
            'ci' => '6858984 LP.',
            'email' => 'nelsonuser@mbos.com',
            'password' => Hash::make('nelsonpassword123'),
            'foto_perfil' => 'perfiles/nelson_tapia.jpg',
        ],
        [
            'ape_paterno' => 'Tarqui',
            'ape_materno' => 'Chura',
            'nombre' => 'Efrain',
            'fecha_nac' => '1990-10-30',
            'ci' => '9239792 LP.',
            'email' => 'efrainuser@mbos.com',
            'password' => Hash::make('efrainpassword123'),
            'foto_perfil' => 'perfiles/efrain_tarqui.jpg',
        ],
        [
            'ape_paterno' => 'Tarqui',
            'ape_materno' => 'Huanca',
            'nombre' => 'Isaac',
            'fecha_nac' => '1987-02-01',
            'ci' => '6875340 LP.',
            'email' => 'isaacuser@mbos.com',
            'password' => Hash::make('isaacpassword123'),
            'foto_perfil' => 'perfiles/isaac_tarqui.jpg',
        ],
        [
            'ape_paterno' => 'Tarquiola',
            'ape_materno' => 'Coria',
            'nombre' => 'Percy',
            'fecha_nac' => '1992-03-11',
            'ci' => '7080473 LP.',
            'email' => 'percyuser@mbos.com',
            'password' => Hash::make('percypassword123'),
            'foto_perfil' => 'perfiles/percy_tarquiola.jpg',
        ],
        [
            'ape_paterno' => 'Valdez',
            'ape_materno' => 'Laura',
            'nombre' => 'Franz Ciro',
            'fecha_nac' => '1985-08-18',
            'ci' => '3461744 LP',
            'email' => 'franzcirouser@mbos.com',
            'password' => Hash::make('franzciropassword123'),
            'foto_perfil' => 'perfiles/franz_valdez.jpg',
        ],
        [
            'ape_paterno' => 'Valeriano',
            'ape_materno' => 'Condori',
            'nombre' => 'Absalón Eleazar',
            'fecha_nac' => '1998-04-14',
            'ci' => '13440376 LP.',
            'email' => 'absaloneleazaruser@mbos.com',
            'password' => Hash::make('absaloneleazarpassword123'),
            'foto_perfil' => 'perfiles/absalon_valeriano.jpg',
        ],
    ];

        foreach($personas as $p){
            DB::table('personas')->insert([
                'nombre' => $p['nombre'],
                'ape_paterno' => $p['ape_paterno'],
                'ape_materno' => $p['ape_materno'],
                'fecha_nac' => $p['fecha_nac'],
                'ci' => $p['ci'],
                'celular' => '0',
                'ciudad' => 'La Paz',
                'zona' => ' ',
                'calle' => null,
                'nro' => null,
                'email' => $p['email'],
                'password'=> $p['password'],
                'estado' => true,
                'foto_perfil' =>$p['foto_perfil'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        } 
    }
}
